version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_TALLYCOIN_CONNECT_IP
      APP_PORT: $APP_TALLYCOIN_CONNECT_PORT

  web:
    image: djbooth007/tallycoin_connect:v1.7.5@sha256:4919b747bc8f67a873739214b1f4b3aab649275641a605cebbd7c7a96f30f6f9
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data:/data
    environment:
      LND_SOCKET: "$APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_GRPC_PORT"
      LND_MACAROON_PATH: "/lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK/admin.macaroon"
      LND_TLSCERT_PATH: "/lnd/tls.cert"
      CONFIG_FILE: "/data/tallycoin_api.key"
      TALLYCOIN_PASSWD_CLEARTEXT: "$APP_PASSWORD"
    networks:
      default:
        ipv4_address: $APP_TALLYCOIN_CONNECT_IP
