version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: tallycoin-connect_web_1
      APP_PORT: 8123

  web:
    image: djbooth007/tallycoin_connect:v1.8.0@sha256:60baba176423640a1a6025d7cdd83b67dcb22a0f1e2ce846b4a765cf98fc79ff
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data:/data
    environment:
      LND_SOCKET: "$APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_GRPC_PORT"
      LND_MACAROON_PATH: "/lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK/admin.macaroon"
      LND_TLSCERT_PATH: "/lnd/tls.cert"
      CONFIG_FILE: "/data/tallycoin_api.key"
      TALLYCOIN_PASSWD_CLEARTEXT: "$APP_PASSWORD"
